"use client";

import { useState, useMemo } from "react";
import type {
  ContentBlock,
  TeacherGuide,
  KeyConceptBlock,
  SpotTheHazardBlock,
} from "@/lib/safety/content-blocks";
import { getBlocksFromBadge } from "@/lib/safety/content-blocks";
import { SCENES } from "@/lib/safety/scenes";

// ============================================================================
// SVG Icons (inline, no lucide-react)
// ============================================================================

const PrintIcon = () => (
  <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
    <polyline points="6 9 6 2 18 2 18 9"></polyline>
    <path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2"></path>
    <rect x="6" y="14" width="12" height="8"></rect>
  </svg>
);

const LaunchIcon = () => (
  <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
    <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"></path>
    <polyline points="15 3 21 3 21 9"></polyline>
    <line x1="10" y1="14" x2="21" y2="3"></line>
  </svg>
);

const ChevronDownIcon = () => (
  <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
    <polyline points="6 9 12 15 18 9"></polyline>
  </svg>
);

const CopyIcon = () => (
  <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
    <rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect>
    <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path>
  </svg>
);

// ============================================================================
// Types
// ============================================================================

type TeachSubTab = "lesson-plan" | "projector" | "discussion" | "stations" | "checklist";

interface TeachTabProps {
  badge: {
    id: string;
    name: string;
    description: string | null;
    learn_content?: Array<{
      id?: string;
      title: string;
      content: string;
      icon: string;
      description?: string;
      tips?: string[];
      examples?: string[];
    }>;
    learning_blocks?: ContentBlock[];
    question_pool?: any[];
  };
  teacherGuide?: TeacherGuide | null;
}

// ============================================================================
// Auto-Generation Helpers
// ============================================================================

/**
 * Calculate estimated lesson duration in minutes
 * 5 min intro + 3 min per learn card/block + 10 min for Spot the Hazard + 5 min per discussion + 5 min wrap-up
 */
function calculateLessonDuration(
  blocks: ContentBlock[],
  discussionCount: number = 3
): number {
  let minutes = 5; // intro
  minutes += blocks.length * 3; // 3 min per block

  // Check if there's a Spot the Hazard block
  const hasHazardBlock = blocks.some((b) => b.type === "spot_the_hazard");
  if (hasHazardBlock) minutes += 10;

  minutes += discussionCount * 5; // discussions
  minutes += 5; // wrap-up

  return minutes;
}

/**
 * Auto-generate discussion prompts from badge content
 */
function autoGenerateDiscussionPrompts(badge: TeachTabProps["badge"]) {
  const blocks = getBlocksFromBadge(badge);
  const prompts = [
    {
      question: `Why do you think ${badge.name.toLowerCase()} is important in our workshop?`,
      expected_responses: [
        "It keeps us safe",
        "It prevents accidents",
        "It protects our health",
      ],
      follow_up: "Can you give a real example of what could happen if we didn't follow these rules?",
    },
    {
      question: "What are the most critical rules you need to remember?",
      expected_responses: blocks
        .filter((b): b is KeyConceptBlock => b.type === "key_concept")
        .slice(0, 3)
        .map((b) => b.title),
      follow_up: "How will you remember these rules when you're working?",
    },
    {
      question: "Have you seen anyone break one of these rules? What happened?",
      expected_responses: [
        "They got hurt",
        "The teacher told them off",
        "They damaged equipment",
      ],
      follow_up: "What should they have done instead?",
    },
    {
      question: "If you see a friend breaking a safety rule, what should you do?",
      expected_responses: [
        "Tell them to stop",
        "Tell the teacher",
        "Help them do it safely",
      ],
      follow_up: "How can you say it in a way that doesn't embarrass them?",
    },
    {
      question: "What would you add to these rules to make the workshop even safer?",
      expected_responses: [
        "Better signage",
        "More first aid kits",
        "A safety buddy system",
      ],
      follow_up: "Why do you think that would help?",
    },
  ];

  return prompts;
}

/**
 * Auto-generate station cards
 */
function autoGenerateStationCards(badge: TeachTabProps["badge"]) {
  const blocks = getBlocksFromBadge(badge);
  const keyConceptBlocks = blocks.filter(
    (b): b is KeyConceptBlock => b.type === "key_concept"
  );

  return keyConceptBlocks.map((block, idx) => ({
    station_name: `Station ${idx + 1}: ${block.title}`,
    rules: [
      block.content.split("\n")[0] || block.title,
      ...(block.examples?.slice(0, 2) || []),
    ],
    qr_code_url: undefined,
    illustration: undefined,
  }));
}

/**
 * Auto-generate checklist
 */
function autoGenerateChecklist(badge: TeachTabProps["badge"]) {
  const blocks = getBlocksFromBadge(badge);
  const keyConceptBlocks = blocks.filter(
    (b): b is KeyConceptBlock => b.type === "key_concept"
  );

  return keyConceptBlocks.map((block) => ({
    criterion: block.title,
    observable_action: block.content.split("\n")[0] || `Student understands ${block.title}`,
  }));
}

/**
 * Auto-generate lesson plan script
 */
function autoGenerateLessonPlan(badge: TeachTabProps["badge"]) {
  const blocks = getBlocksFromBadge(badge);
  const script: Array<{
    step: number;
    action: string;
    say: string;
    show: string;
    timing_seconds: number;
  }> = [];

  let step = 1;

  // Opening
  script.push({
    step,
    action: "Welcome & hook",
    say: `Today we're learning about ${badge.name}. This is important because it keeps you and everyone else safe in our workshop.`,
    show: `Badge name and description on projector`,
    timing_seconds: 300,
  });
  step++;

  // Key concepts
  const keyConceptBlocks = blocks.filter(
    (b): b is KeyConceptBlock => b.type === "key_concept"
  );
  keyConceptBlocks.forEach((block) => {
    script.push({
      step,
      action: `Present: ${block.title}`,
      say: block.content,
      show: block.title,
      timing_seconds: 180,
    });
    step++;
  });

  // Spot the Hazard activity
  const hazardBlock = blocks.find(
    (b): b is SpotTheHazardBlock => b.type === "spot_the_hazard"
  );
  if (hazardBlock) {
    script.push({
      step,
      action: "Interactive: Spot the Hazard",
      say: `Now let's test what you've learned. I'm going to show you a workshop scene. Can you spot all the safety hazards? Think about what could go wrong and how we'd fix it.`,
      show: `Workshop scene - students spot hazards`,
      timing_seconds: 600,
    });
    step++;
  }

  // Discussion
  script.push({
    step,
    action: "Group discussion",
    say: `Why do you think these rules matter? Has anyone seen something unsafe before?`,
    show: `Discussion prompts on projector`,
    timing_seconds: 300,
  });
  step++;

  // Wrap-up
  script.push({
    step,
    action: "Conclusion",
    say: `Remember: safety is everyone's responsibility. If you see something unsafe, speak up. Let's make our workshop the safest place in school.`,
    show: `Key rules summary`,
    timing_seconds: 300,
  });

  return script;
}

// ============================================================================
// Sub-components
// ============================================================================

function LessonPlanTab({
  badge,
  script,
}: {
  badge: TeachTabProps["badge"];
  script: Array<{
    step: number;
    action: string;
    say: string;
    show: string;
    timing_seconds: number;
  }>;
}) {
  const duration = useMemo(() => {
    const blocks = getBlocksFromBadge(badge);
    return calculateLessonDuration(blocks);
  }, [badge]);

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h3 className="text-lg font-semibold text-gray-900">{badge.name} Lesson Plan</h3>
          <p className="text-sm text-gray-600 mt-1">
            Estimated duration: <span className="font-semibold">{duration} minutes</span>
          </p>
        </div>
        <button
          onClick={handlePrint}
          className="flex items-center gap-2 px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition-colors"
        >
          <PrintIcon /> Print
        </button>
      </div>

      <div className="space-y-4">
        {script.map((step) => (
          <div key={step.step} className="border border-gray-200 rounded-lg p-5 bg-white">
            <div className="flex items-start gap-4">
              <div className="flex-shrink-0 w-8 h-8 rounded-full bg-purple-600 text-white flex items-center justify-center font-semibold text-sm">
                {step.step}
              </div>
              <div className="flex-grow space-y-3">
                <h4 className="font-semibold text-gray-900">{step.action}</h4>

                {/* Timing badge */}
                <div className="text-xs text-gray-500 flex items-center gap-2">
                  <span className="inline-block w-1.5 h-1.5 rounded-full bg-gray-400"></span>
                  {Math.round(step.timing_seconds / 60)} minutes
                </div>

                {/* Say (blue callout) */}
                <div className="bg-blue-50 border-l-4 border-blue-500 p-3 rounded">
                  <p className="text-xs font-semibold text-blue-900 mb-1">WHAT TO SAY</p>
                  <p className="text-sm text-blue-800 leading-relaxed">{step.say}</p>
                </div>

                {/* Show (purple callout) */}
                <div className="bg-purple-50 border-l-4 border-purple-500 p-3 rounded">
                  <p className="text-xs font-semibold text-purple-900 mb-1">WHAT TO SHOW</p>
                  <p className="text-sm text-purple-800 leading-relaxed">{step.show}</p>
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

function ProjectorViewTab({ badge }: { badge: TeachTabProps["badge"] }) {
  const handleLaunchProjector = () => {
    const projectorUrl = `/safety/projector/${badge.id}`;
    window.open(projectorUrl, "projector", "width=1280,height=720");
  };

  const blocks = getBlocksFromBadge(badge);
  const slideCount = 2 + blocks.length; // title + content blocks + hazards

  return (
    <div className="space-y-6">
      <div className="bg-gradient-to-r from-purple-50 to-purple-100 border border-purple-200 rounded-lg p-6">
        <h3 className="font-semibold text-gray-900 mb-2">Launch Presentation Mode</h3>
        <p className="text-sm text-gray-700 mb-4">
          Open this lesson in a presentation-friendly format. Perfect for displaying on a classroom
          projector. ~{slideCount} slides total.
        </p>
        <button
          onClick={handleLaunchProjector}
          className="flex items-center gap-2 px-6 py-3 bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition-colors font-semibold"
        >
          <LaunchIcon /> Launch Projector View
        </button>
      </div>

      <div className="bg-gray-900 rounded-lg p-6 text-white text-center min-h-64 flex flex-col items-center justify-center">
        <div className="text-4xl font-bold mb-2">{badge.name}</div>
        <p className="text-gray-300 text-sm mb-6 max-w-md">{badge.description}</p>
        <p className="text-xs text-gray-500">(Preview of what students will see)</p>
      </div>

      <div className="grid grid-cols-2 gap-3 text-xs text-gray-600">
        <div className="bg-gray-50 p-3 rounded">
          <p className="font-semibold text-gray-900 mb-1">📊 Slides Included</p>
          <ul className="space-y-1 text-gray-700">
            <li>• Title slide</li>
            <li>• {blocks.length} concept slides</li>
            <li>• Interactive activities</li>
            <li>• Summary</li>
          </ul>
        </div>
        <div className="bg-gray-50 p-3 rounded">
          <p className="font-semibold text-gray-900 mb-1">✨ Features</p>
          <ul className="space-y-1 text-gray-700">
            <li>• Large, readable text</li>
            <li>• Dark background</li>
            <li>• One concept at a time</li>
            <li>• Navigation arrows</li>
          </ul>
        </div>
      </div>
    </div>
  );
}

function DiscussionPromptsTab({
  prompts,
}: {
  prompts: Array<{
    question: string;
    expected_responses: string[];
    follow_up: string;
  }>;
}) {
  const [expandedId, setExpandedId] = useState<number | null>(0);

  const handleCopyPrompt = (question: string) => {
    navigator.clipboard.writeText(question);
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between mb-4">
        <h3 className="text-lg font-semibold text-gray-900">Discussion Prompts</h3>
        <p className="text-sm text-gray-600">{prompts.length} prompts</p>
      </div>

      {prompts.map((prompt, idx) => (
        <div key={idx} className="border border-gray-200 rounded-lg overflow-hidden bg-white">
          <button
            onClick={() => setExpandedId(expandedId === idx ? null : idx)}
            className="w-full px-5 py-4 flex items-start gap-3 hover:bg-gray-50 transition-colors text-left"
          >
            <ChevronDownIcon />
            <div className="flex-grow">
              <p className="font-semibold text-gray-900 text-base leading-snug">
                {prompt.question}
              </p>
            </div>
            <button
              onClick={(e) => {
                e.stopPropagation();
                handleCopyPrompt(prompt.question);
              }}
              className="flex-shrink-0 p-2 text-gray-500 hover:text-purple-600 transition-colors"
              title="Copy to clipboard"
            >
              <CopyIcon />
            </button>
          </button>

          {expandedId === idx && (
            <div className="border-t border-gray-200 px-5 py-4 bg-gray-50 space-y-4">
              <div>
                <p className="text-xs font-semibold text-gray-700 mb-2 uppercase">
                  Expected Student Responses
                </p>
                <ul className="space-y-2">
                  {prompt.expected_responses.map((response, rIdx) => (
                    <li key={rIdx} className="flex items-start gap-2 text-sm text-gray-700">
                      <span className="text-purple-500 font-bold mt-0.5">•</span>
                      {response}
                    </li>
                  ))}
                </ul>
              </div>

              <div className="bg-blue-50 border-l-4 border-blue-500 p-3 rounded">
                <p className="text-xs font-semibold text-blue-900 mb-1">FOLLOW-UP QUESTION</p>
                <p className="text-sm text-blue-800">{prompt.follow_up}</p>
              </div>
            </div>
          )}
        </div>
      ))}
    </div>
  );
}

function StationCardsTab({
  cards,
  badgeName,
}: {
  cards: Array<{ station_name: string; rules: string[]; qr_code_url?: string }>;
  badgeName: string;
}) {
  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h3 className="text-lg font-semibold text-gray-900">Printable Station Cards</h3>
          <p className="text-sm text-gray-600 mt-1">A5-sized cards for workshop stations</p>
        </div>
        <button
          onClick={handlePrint}
          className="flex items-center gap-2 px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition-colors"
        >
          <PrintIcon /> Print Cards
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {cards.map((card, idx) => (
          <div
            key={idx}
            className="bg-white border-2 border-gray-300 rounded-lg overflow-hidden shadow-md print:break-inside-avoid"
            style={{ aspectRatio: "5/7" }}
          >
            {/* Card header */}
            <div className="bg-purple-600 text-white px-4 py-3 text-center border-b-2 border-gray-300">
              <p className="text-xs font-semibold uppercase tracking-wider">Station</p>
              <p className="text-2xl font-bold">{idx + 1}</p>
            </div>

            {/* Card content */}
            <div className="px-4 py-3 space-y-3 text-center">
              <p className="font-semibold text-gray-900 text-sm leading-tight">
                {card.station_name.replace(/^Station \d+: /, "")}
              </p>

              <div className="space-y-2">
                <p className="text-xs font-semibold text-gray-600 uppercase">Rules</p>
                <ol className="text-xs text-gray-700 space-y-1">
                  {card.rules.slice(0, 3).map((rule, rIdx) => (
                    <li key={rIdx} className="text-left leading-snug">
                      <span className="font-bold">{rIdx + 1}.</span> {rule}
                    </li>
                  ))}
                </ol>
              </div>

              {card.qr_code_url && (
                <div className="text-xs text-gray-600 pt-2">
                  <p className="font-semibold mb-1">QR Code</p>
                  <p className="text-gray-500">[Placeholder for QR]</p>
                </div>
              )}
            </div>
          </div>
        ))}
      </div>

      <style>{`
        @media print {
          body {
            margin: 0;
            padding: 0;
          }
          .print\\:break-inside-avoid {
            break-inside: avoid;
          }
        }
      `}</style>
    </div>
  );
}

function ChecklistTab({
  checklist,
  badgeName,
}: {
  checklist: Array<{ criterion: string; observable_action: string }>;
  badgeName: string;
}) {
  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h3 className="text-lg font-semibold text-gray-900">Teacher Observation Checklist</h3>
          <p className="text-sm text-gray-600 mt-1">Printable checklist for assessing students</p>
        </div>
        <button
          onClick={handlePrint}
          className="flex items-center gap-2 px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition-colors"
        >
          <PrintIcon /> Print
        </button>
      </div>

      <div className="bg-white border border-gray-200 rounded-lg overflow-hidden">
        {/* Header */}
        <div className="bg-purple-50 px-6 py-4 border-b border-gray-200">
          <h4 className="font-semibold text-gray-900">{badgeName}</h4>
          <div className="grid grid-cols-3 gap-4 mt-3 text-xs text-gray-600">
            <div>
              <p className="font-semibold text-gray-900">Student Name:</p>
              <p className="mt-1 border-b border-dashed border-gray-300 py-1">
                ________________________________
              </p>
            </div>
            <div>
              <p className="font-semibold text-gray-900">Date:</p>
              <p className="mt-1 border-b border-dashed border-gray-300 py-1">
                ________________________________
              </p>
            </div>
            <div>
              <p className="font-semibold text-gray-900">Observer:</p>
              <p className="mt-1 border-b border-dashed border-gray-300 py-1">
                ________________________________
              </p>
            </div>
          </div>
        </div>

        {/* Checklist rows */}
        <div className="divide-y divide-gray-200">
          {checklist.map((item, idx) => (
            <div key={idx} className="px-6 py-4 flex gap-4">
              <div className="flex-shrink-0 pt-1">
                <input
                  type="checkbox"
                  className="w-5 h-5 text-purple-600 border-gray-300 rounded cursor-pointer"
                  disabled
                />
              </div>
              <div className="flex-grow min-w-0">
                <p className="font-semibold text-gray-900 text-sm">{item.criterion}</p>
                <p className="text-xs text-gray-600 mt-1">{item.observable_action}</p>
              </div>
            </div>
          ))}
        </div>

        {/* Footer */}
        <div className="px-6 py-4 bg-gray-50 border-t border-gray-200">
          <p className="text-xs text-gray-600 italic">
            Observation notes: ________________________________________________________________
          </p>
        </div>
      </div>

      <style>{`
        @media print {
          body {
            margin: 0;
            padding: 8mm;
            font-size: 11pt;
          }
        }
      `}</style>
    </div>
  );
}

// ============================================================================
// Main Component
// ============================================================================

export default function TeachTab({ badge, teacherGuide }: TeachTabProps) {
  const [activeTab, setActiveTab] = useState<TeachSubTab>("lesson-plan");

  // Prepare data
  const lessonScript = teacherGuide?.demo_script || autoGenerateLessonPlan(badge);
  const discussionPrompts = teacherGuide?.discussion_prompts || autoGenerateDiscussionPrompts(badge);
  const stationCards = teacherGuide?.station_cards || autoGenerateStationCards(badge);
  const checklist = teacherGuide?.practical_checklist || autoGenerateChecklist(badge);

  const tabs: Array<{ id: TeachSubTab; label: string }> = [
    { id: "lesson-plan", label: "Lesson Plan" },
    { id: "projector", label: "Projector View" },
    { id: "discussion", label: "Discussion Prompts" },
    { id: "stations", label: "Station Cards" },
    { id: "checklist", label: "Checklist" },
  ];

  return (
    <div className="space-y-6">
      {/* Sub-tabs */}
      <div className="flex gap-2 border-b border-gray-200 overflow-x-auto">
        {tabs.map((tab) => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id)}
            className={`px-4 py-3 font-medium text-sm whitespace-nowrap border-b-2 transition-colors ${
              activeTab === tab.id
                ? "border-purple-600 text-purple-600"
                : "border-transparent text-gray-600 hover:text-gray-900"
            }`}
          >
            {tab.label}
          </button>
        ))}
      </div>

      {/* Tab content */}
      <div>
        {activeTab === "lesson-plan" && <LessonPlanTab badge={badge} script={lessonScript} />}
        {activeTab === "projector" && <ProjectorViewTab badge={badge} />}
        {activeTab === "discussion" && <DiscussionPromptsTab prompts={discussionPrompts} />}
        {activeTab === "stations" && (
          <StationCardsTab cards={stationCards} badgeName={badge.name} />
        )}
        {activeTab === "checklist" && (
          <ChecklistTab checklist={checklist} badgeName={badge.name} />
        )}
      </div>
    </div>
  );
}
