-- Migration: phase_1_4_cs2_fix_class_students_classes_recursion
-- Created: 20260430015239 UTC
--
-- WHY: <one paragraph — what problem does this migration solve?>
-- IMPACT: <which tables/columns/indexes/RLS policies change?>
-- ROLLBACK: paired .down.sql undoes this migration.
--
-- Claim discipline: commit + push this stub IMMEDIATELY (before writing
-- the SQL body) so the timestamp is reserved on origin. See
-- scripts/migrations/new-migration.sh for the full ritual.

-- TODO: write SQL here
